######################################################################
# Automatically generated by qmake (3.0) Fri Apr 17 08:27:20 2015
######################################################################

TEMPLATE = lib
TARGET = meatools
DESTDIR += ../lib
OBJECTS_DIR += ../build
INCLUDEPATH += . /usr/local/include
LIBS += -L/usr/local/lib -lhdf5
CONFIG += debug_and_release

# Input
HEADERS += bintools.h hdftools.h
SOURCES += bintools.c hdftools.c
