######################################################################
# Automatically generated by qmake (3.0) Tue Oct 4 11:15:20 2016
######################################################################

TEMPLATE = app
TARGET = test_libdatafile
INCLUDEPATH += . \
	/usr/local/include \
	/usr/include \
	../include \
	../../libmea-device/include

LIBS += -L/usr/local/lib -L../lib/ \
	-ldatafile -larmadillo -lhdf5_cpp -lhdf5

QT += testlib
CONFIG += testcase debug c++11
CONFIG -= app_bundle

QMAKE_RPATHDIR += ../lib/

# Input
HEADERS += test_libdatafile.h
SOURCES += test_libdatafile.cc
