// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: logserver.proto

#ifndef PROTOBUF_logserver_2eproto__INCLUDED
#define PROTOBUF_logserver_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace mearec {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_logserver_2eproto();
void protobuf_AssignDesc_logserver_2eproto();
void protobuf_ShutdownFile_logserver_2eproto();

class RecordingStatusRequest;
class RecordingStatusReply;

enum RecordingStatusReply_StatusType {
  RecordingStatusReply_StatusType_RUNNING = 0,
  RecordingStatusReply_StatusType_STOPPED = 1,
  RecordingStatusReply_StatusType_ERROR = 2
};
bool RecordingStatusReply_StatusType_IsValid(int value);
const RecordingStatusReply_StatusType RecordingStatusReply_StatusType_StatusType_MIN = RecordingStatusReply_StatusType_RUNNING;
const RecordingStatusReply_StatusType RecordingStatusReply_StatusType_StatusType_MAX = RecordingStatusReply_StatusType_ERROR;
const int RecordingStatusReply_StatusType_StatusType_ARRAYSIZE = RecordingStatusReply_StatusType_StatusType_MAX + 1;

const ::google::protobuf::EnumDescriptor* RecordingStatusReply_StatusType_descriptor();
inline const ::std::string& RecordingStatusReply_StatusType_Name(RecordingStatusReply_StatusType value) {
  return ::google::protobuf::internal::NameOfEnum(
    RecordingStatusReply_StatusType_descriptor(), value);
}
inline bool RecordingStatusReply_StatusType_Parse(
    const ::std::string& name, RecordingStatusReply_StatusType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<RecordingStatusReply_StatusType>(
    RecordingStatusReply_StatusType_descriptor(), name, value);
}
// ===================================================================

class RecordingStatusRequest : public ::google::protobuf::Message {
 public:
  RecordingStatusRequest();
  virtual ~RecordingStatusRequest();

  RecordingStatusRequest(const RecordingStatusRequest& from);

  inline RecordingStatusRequest& operator=(const RecordingStatusRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RecordingStatusRequest& default_instance();

  void Swap(RecordingStatusRequest* other);

  // implements Message ----------------------------------------------

  RecordingStatusRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RecordingStatusRequest& from);
  void MergeFrom(const RecordingStatusRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bool status = 1;
  inline bool has_status() const;
  inline void clear_status();
  static const int kStatusFieldNumber = 1;
  inline bool status() const;
  inline void set_status(bool value);

  // optional bool filename = 2;
  inline bool has_filename() const;
  inline void clear_filename();
  static const int kFilenameFieldNumber = 2;
  inline bool filename() const;
  inline void set_filename(bool value);

  // optional bool length = 3;
  inline bool has_length() const;
  inline void clear_length();
  static const int kLengthFieldNumber = 3;
  inline bool length() const;
  inline void set_length(bool value);

  // optional bool nsamples = 4;
  inline bool has_nsamples() const;
  inline void clear_nsamples();
  static const int kNsamplesFieldNumber = 4;
  inline bool nsamples() const;
  inline void set_nsamples(bool value);

  // optional bool nchannels = 5;
  inline bool has_nchannels() const;
  inline void clear_nchannels();
  static const int kNchannelsFieldNumber = 5;
  inline bool nchannels() const;
  inline void set_nchannels(bool value);

  // optional bool lastValidSample = 6;
  inline bool has_lastvalidsample() const;
  inline void clear_lastvalidsample();
  static const int kLastValidSampleFieldNumber = 6;
  inline bool lastvalidsample() const;
  inline void set_lastvalidsample(bool value);

  // optional bool blockSize = 7;
  inline bool has_blocksize() const;
  inline void clear_blocksize();
  static const int kBlockSizeFieldNumber = 7;
  inline bool blocksize() const;
  inline void set_blocksize(bool value);

  // optional bool sampleRate = 8;
  inline bool has_samplerate() const;
  inline void clear_samplerate();
  static const int kSampleRateFieldNumber = 8;
  inline bool samplerate() const;
  inline void set_samplerate(bool value);

  // optional bool gain = 9;
  inline bool has_gain() const;
  inline void clear_gain();
  static const int kGainFieldNumber = 9;
  inline bool gain() const;
  inline void set_gain(bool value);

  // optional bool offset = 10;
  inline bool has_offset() const;
  inline void clear_offset();
  static const int kOffsetFieldNumber = 10;
  inline bool offset() const;
  inline void set_offset(bool value);

  // optional bool date = 11;
  inline bool has_date() const;
  inline void clear_date();
  static const int kDateFieldNumber = 11;
  inline bool date() const;
  inline void set_date(bool value);

  // optional bool time = 12;
  inline bool has_time() const;
  inline void clear_time();
  static const int kTimeFieldNumber = 12;
  inline bool time() const;
  inline void set_time(bool value);

  // @@protoc_insertion_point(class_scope:mearec.RecordingStatusRequest)
 private:
  inline void set_has_status();
  inline void clear_has_status();
  inline void set_has_filename();
  inline void clear_has_filename();
  inline void set_has_length();
  inline void clear_has_length();
  inline void set_has_nsamples();
  inline void clear_has_nsamples();
  inline void set_has_nchannels();
  inline void clear_has_nchannels();
  inline void set_has_lastvalidsample();
  inline void clear_has_lastvalidsample();
  inline void set_has_blocksize();
  inline void clear_has_blocksize();
  inline void set_has_samplerate();
  inline void clear_has_samplerate();
  inline void set_has_gain();
  inline void clear_has_gain();
  inline void set_has_offset();
  inline void clear_has_offset();
  inline void set_has_date();
  inline void clear_has_date();
  inline void set_has_time();
  inline void clear_has_time();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  bool status_;
  bool filename_;
  bool length_;
  bool nsamples_;
  bool nchannels_;
  bool lastvalidsample_;
  bool blocksize_;
  bool samplerate_;
  bool gain_;
  bool offset_;
  bool date_;
  bool time_;
  friend void  protobuf_AddDesc_logserver_2eproto();
  friend void protobuf_AssignDesc_logserver_2eproto();
  friend void protobuf_ShutdownFile_logserver_2eproto();

  void InitAsDefaultInstance();
  static RecordingStatusRequest* default_instance_;
};
// -------------------------------------------------------------------

class RecordingStatusReply : public ::google::protobuf::Message {
 public:
  RecordingStatusReply();
  virtual ~RecordingStatusReply();

  RecordingStatusReply(const RecordingStatusReply& from);

  inline RecordingStatusReply& operator=(const RecordingStatusReply& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RecordingStatusReply& default_instance();

  void Swap(RecordingStatusReply* other);

  // implements Message ----------------------------------------------

  RecordingStatusReply* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RecordingStatusReply& from);
  void MergeFrom(const RecordingStatusReply& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef RecordingStatusReply_StatusType StatusType;
  static const StatusType RUNNING = RecordingStatusReply_StatusType_RUNNING;
  static const StatusType STOPPED = RecordingStatusReply_StatusType_STOPPED;
  static const StatusType ERROR = RecordingStatusReply_StatusType_ERROR;
  static inline bool StatusType_IsValid(int value) {
    return RecordingStatusReply_StatusType_IsValid(value);
  }
  static const StatusType StatusType_MIN =
    RecordingStatusReply_StatusType_StatusType_MIN;
  static const StatusType StatusType_MAX =
    RecordingStatusReply_StatusType_StatusType_MAX;
  static const int StatusType_ARRAYSIZE =
    RecordingStatusReply_StatusType_StatusType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  StatusType_descriptor() {
    return RecordingStatusReply_StatusType_descriptor();
  }
  static inline const ::std::string& StatusType_Name(StatusType value) {
    return RecordingStatusReply_StatusType_Name(value);
  }
  static inline bool StatusType_Parse(const ::std::string& name,
      StatusType* value) {
    return RecordingStatusReply_StatusType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // optional .mearec.RecordingStatusReply.StatusType status = 1;
  inline bool has_status() const;
  inline void clear_status();
  static const int kStatusFieldNumber = 1;
  inline ::mearec::RecordingStatusReply_StatusType status() const;
  inline void set_status(::mearec::RecordingStatusReply_StatusType value);

  // optional string filename = 2;
  inline bool has_filename() const;
  inline void clear_filename();
  static const int kFilenameFieldNumber = 2;
  inline const ::std::string& filename() const;
  inline void set_filename(const ::std::string& value);
  inline void set_filename(const char* value);
  inline void set_filename(const char* value, size_t size);
  inline ::std::string* mutable_filename();
  inline ::std::string* release_filename();
  inline void set_allocated_filename(::std::string* filename);

  // optional double length = 3;
  inline bool has_length() const;
  inline void clear_length();
  static const int kLengthFieldNumber = 3;
  inline double length() const;
  inline void set_length(double value);

  // optional uint32 nsamples = 4;
  inline bool has_nsamples() const;
  inline void clear_nsamples();
  static const int kNsamplesFieldNumber = 4;
  inline ::google::protobuf::uint32 nsamples() const;
  inline void set_nsamples(::google::protobuf::uint32 value);

  // optional uint32 nchannels = 5;
  inline bool has_nchannels() const;
  inline void clear_nchannels();
  static const int kNchannelsFieldNumber = 5;
  inline ::google::protobuf::uint32 nchannels() const;
  inline void set_nchannels(::google::protobuf::uint32 value);

  // optional uint32 lastValidSample = 6;
  inline bool has_lastvalidsample() const;
  inline void clear_lastvalidsample();
  static const int kLastValidSampleFieldNumber = 6;
  inline ::google::protobuf::uint32 lastvalidsample() const;
  inline void set_lastvalidsample(::google::protobuf::uint32 value);

  // optional uint32 blockSize = 7;
  inline bool has_blocksize() const;
  inline void clear_blocksize();
  static const int kBlockSizeFieldNumber = 7;
  inline ::google::protobuf::uint32 blocksize() const;
  inline void set_blocksize(::google::protobuf::uint32 value);

  // optional float sampleRate = 8;
  inline bool has_samplerate() const;
  inline void clear_samplerate();
  static const int kSampleRateFieldNumber = 8;
  inline float samplerate() const;
  inline void set_samplerate(float value);

  // optional float gain = 9;
  inline bool has_gain() const;
  inline void clear_gain();
  static const int kGainFieldNumber = 9;
  inline float gain() const;
  inline void set_gain(float value);

  // optional float offset = 10;
  inline bool has_offset() const;
  inline void clear_offset();
  static const int kOffsetFieldNumber = 10;
  inline float offset() const;
  inline void set_offset(float value);

  // optional string date = 11;
  inline bool has_date() const;
  inline void clear_date();
  static const int kDateFieldNumber = 11;
  inline const ::std::string& date() const;
  inline void set_date(const ::std::string& value);
  inline void set_date(const char* value);
  inline void set_date(const char* value, size_t size);
  inline ::std::string* mutable_date();
  inline ::std::string* release_date();
  inline void set_allocated_date(::std::string* date);

  // optional string time = 12;
  inline bool has_time() const;
  inline void clear_time();
  static const int kTimeFieldNumber = 12;
  inline const ::std::string& time() const;
  inline void set_time(const ::std::string& value);
  inline void set_time(const char* value);
  inline void set_time(const char* value, size_t size);
  inline ::std::string* mutable_time();
  inline ::std::string* release_time();
  inline void set_allocated_time(::std::string* time);

  // @@protoc_insertion_point(class_scope:mearec.RecordingStatusReply)
 private:
  inline void set_has_status();
  inline void clear_has_status();
  inline void set_has_filename();
  inline void clear_has_filename();
  inline void set_has_length();
  inline void clear_has_length();
  inline void set_has_nsamples();
  inline void clear_has_nsamples();
  inline void set_has_nchannels();
  inline void clear_has_nchannels();
  inline void set_has_lastvalidsample();
  inline void clear_has_lastvalidsample();
  inline void set_has_blocksize();
  inline void clear_has_blocksize();
  inline void set_has_samplerate();
  inline void clear_has_samplerate();
  inline void set_has_gain();
  inline void clear_has_gain();
  inline void set_has_offset();
  inline void clear_has_offset();
  inline void set_has_date();
  inline void clear_has_date();
  inline void set_has_time();
  inline void clear_has_time();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* filename_;
  int status_;
  ::google::protobuf::uint32 nsamples_;
  double length_;
  ::google::protobuf::uint32 nchannels_;
  ::google::protobuf::uint32 lastvalidsample_;
  ::google::protobuf::uint32 blocksize_;
  float samplerate_;
  float gain_;
  float offset_;
  ::std::string* date_;
  ::std::string* time_;
  friend void  protobuf_AddDesc_logserver_2eproto();
  friend void protobuf_AssignDesc_logserver_2eproto();
  friend void protobuf_ShutdownFile_logserver_2eproto();

  void InitAsDefaultInstance();
  static RecordingStatusReply* default_instance_;
};
// ===================================================================


// ===================================================================

// RecordingStatusRequest

// optional bool status = 1;
inline bool RecordingStatusRequest::has_status() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RecordingStatusRequest::set_has_status() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RecordingStatusRequest::clear_has_status() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RecordingStatusRequest::clear_status() {
  status_ = false;
  clear_has_status();
}
inline bool RecordingStatusRequest::status() const {
  // @@protoc_insertion_point(field_get:mearec.RecordingStatusRequest.status)
  return status_;
}
inline void RecordingStatusRequest::set_status(bool value) {
  set_has_status();
  status_ = value;
  // @@protoc_insertion_point(field_set:mearec.RecordingStatusRequest.status)
}

// optional bool filename = 2;
inline bool RecordingStatusRequest::has_filename() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RecordingStatusRequest::set_has_filename() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RecordingStatusRequest::clear_has_filename() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RecordingStatusRequest::clear_filename() {
  filename_ = false;
  clear_has_filename();
}
inline bool RecordingStatusRequest::filename() const {
  // @@protoc_insertion_point(field_get:mearec.RecordingStatusRequest.filename)
  return filename_;
}
inline void RecordingStatusRequest::set_filename(bool value) {
  set_has_filename();
  filename_ = value;
  // @@protoc_insertion_point(field_set:mearec.RecordingStatusRequest.filename)
}

// optional bool length = 3;
inline bool RecordingStatusRequest::has_length() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void RecordingStatusRequest::set_has_length() {
  _has_bits_[0] |= 0x00000004u;
}
inline void RecordingStatusRequest::clear_has_length() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void RecordingStatusRequest::clear_length() {
  length_ = false;
  clear_has_length();
}
inline bool RecordingStatusRequest::length() const {
  // @@protoc_insertion_point(field_get:mearec.RecordingStatusRequest.length)
  return length_;
}
inline void RecordingStatusRequest::set_length(bool value) {
  set_has_length();
  length_ = value;
  // @@protoc_insertion_point(field_set:mearec.RecordingStatusRequest.length)
}

// optional bool nsamples = 4;
inline bool RecordingStatusRequest::has_nsamples() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void RecordingStatusRequest::set_has_nsamples() {
  _has_bits_[0] |= 0x00000008u;
}
inline void RecordingStatusRequest::clear_has_nsamples() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void RecordingStatusRequest::clear_nsamples() {
  nsamples_ = false;
  clear_has_nsamples();
}
inline bool RecordingStatusRequest::nsamples() const {
  // @@protoc_insertion_point(field_get:mearec.RecordingStatusRequest.nsamples)
  return nsamples_;
}
inline void RecordingStatusRequest::set_nsamples(bool value) {
  set_has_nsamples();
  nsamples_ = value;
  // @@protoc_insertion_point(field_set:mearec.RecordingStatusRequest.nsamples)
}

// optional bool nchannels = 5;
inline bool RecordingStatusRequest::has_nchannels() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void RecordingStatusRequest::set_has_nchannels() {
  _has_bits_[0] |= 0x00000010u;
}
inline void RecordingStatusRequest::clear_has_nchannels() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void RecordingStatusRequest::clear_nchannels() {
  nchannels_ = false;
  clear_has_nchannels();
}
inline bool RecordingStatusRequest::nchannels() const {
  // @@protoc_insertion_point(field_get:mearec.RecordingStatusRequest.nchannels)
  return nchannels_;
}
inline void RecordingStatusRequest::set_nchannels(bool value) {
  set_has_nchannels();
  nchannels_ = value;
  // @@protoc_insertion_point(field_set:mearec.RecordingStatusRequest.nchannels)
}

// optional bool lastValidSample = 6;
inline bool RecordingStatusRequest::has_lastvalidsample() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void RecordingStatusRequest::set_has_lastvalidsample() {
  _has_bits_[0] |= 0x00000020u;
}
inline void RecordingStatusRequest::clear_has_lastvalidsample() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void RecordingStatusRequest::clear_lastvalidsample() {
  lastvalidsample_ = false;
  clear_has_lastvalidsample();
}
inline bool RecordingStatusRequest::lastvalidsample() const {
  // @@protoc_insertion_point(field_get:mearec.RecordingStatusRequest.lastValidSample)
  return lastvalidsample_;
}
inline void RecordingStatusRequest::set_lastvalidsample(bool value) {
  set_has_lastvalidsample();
  lastvalidsample_ = value;
  // @@protoc_insertion_point(field_set:mearec.RecordingStatusRequest.lastValidSample)
}

// optional bool blockSize = 7;
inline bool RecordingStatusRequest::has_blocksize() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void RecordingStatusRequest::set_has_blocksize() {
  _has_bits_[0] |= 0x00000040u;
}
inline void RecordingStatusRequest::clear_has_blocksize() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void RecordingStatusRequest::clear_blocksize() {
  blocksize_ = false;
  clear_has_blocksize();
}
inline bool RecordingStatusRequest::blocksize() const {
  // @@protoc_insertion_point(field_get:mearec.RecordingStatusRequest.blockSize)
  return blocksize_;
}
inline void RecordingStatusRequest::set_blocksize(bool value) {
  set_has_blocksize();
  blocksize_ = value;
  // @@protoc_insertion_point(field_set:mearec.RecordingStatusRequest.blockSize)
}

// optional bool sampleRate = 8;
inline bool RecordingStatusRequest::has_samplerate() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void RecordingStatusRequest::set_has_samplerate() {
  _has_bits_[0] |= 0x00000080u;
}
inline void RecordingStatusRequest::clear_has_samplerate() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void RecordingStatusRequest::clear_samplerate() {
  samplerate_ = false;
  clear_has_samplerate();
}
inline bool RecordingStatusRequest::samplerate() const {
  // @@protoc_insertion_point(field_get:mearec.RecordingStatusRequest.sampleRate)
  return samplerate_;
}
inline void RecordingStatusRequest::set_samplerate(bool value) {
  set_has_samplerate();
  samplerate_ = value;
  // @@protoc_insertion_point(field_set:mearec.RecordingStatusRequest.sampleRate)
}

// optional bool gain = 9;
inline bool RecordingStatusRequest::has_gain() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void RecordingStatusRequest::set_has_gain() {
  _has_bits_[0] |= 0x00000100u;
}
inline void RecordingStatusRequest::clear_has_gain() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void RecordingStatusRequest::clear_gain() {
  gain_ = false;
  clear_has_gain();
}
inline bool RecordingStatusRequest::gain() const {
  // @@protoc_insertion_point(field_get:mearec.RecordingStatusRequest.gain)
  return gain_;
}
inline void RecordingStatusRequest::set_gain(bool value) {
  set_has_gain();
  gain_ = value;
  // @@protoc_insertion_point(field_set:mearec.RecordingStatusRequest.gain)
}

// optional bool offset = 10;
inline bool RecordingStatusRequest::has_offset() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void RecordingStatusRequest::set_has_offset() {
  _has_bits_[0] |= 0x00000200u;
}
inline void RecordingStatusRequest::clear_has_offset() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void RecordingStatusRequest::clear_offset() {
  offset_ = false;
  clear_has_offset();
}
inline bool RecordingStatusRequest::offset() const {
  // @@protoc_insertion_point(field_get:mearec.RecordingStatusRequest.offset)
  return offset_;
}
inline void RecordingStatusRequest::set_offset(bool value) {
  set_has_offset();
  offset_ = value;
  // @@protoc_insertion_point(field_set:mearec.RecordingStatusRequest.offset)
}

// optional bool date = 11;
inline bool RecordingStatusRequest::has_date() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void RecordingStatusRequest::set_has_date() {
  _has_bits_[0] |= 0x00000400u;
}
inline void RecordingStatusRequest::clear_has_date() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void RecordingStatusRequest::clear_date() {
  date_ = false;
  clear_has_date();
}
inline bool RecordingStatusRequest::date() const {
  // @@protoc_insertion_point(field_get:mearec.RecordingStatusRequest.date)
  return date_;
}
inline void RecordingStatusRequest::set_date(bool value) {
  set_has_date();
  date_ = value;
  // @@protoc_insertion_point(field_set:mearec.RecordingStatusRequest.date)
}

// optional bool time = 12;
inline bool RecordingStatusRequest::has_time() const {
  return (_has_bits_[0] & 0x00000800u) != 0;
}
inline void RecordingStatusRequest::set_has_time() {
  _has_bits_[0] |= 0x00000800u;
}
inline void RecordingStatusRequest::clear_has_time() {
  _has_bits_[0] &= ~0x00000800u;
}
inline void RecordingStatusRequest::clear_time() {
  time_ = false;
  clear_has_time();
}
inline bool RecordingStatusRequest::time() const {
  // @@protoc_insertion_point(field_get:mearec.RecordingStatusRequest.time)
  return time_;
}
inline void RecordingStatusRequest::set_time(bool value) {
  set_has_time();
  time_ = value;
  // @@protoc_insertion_point(field_set:mearec.RecordingStatusRequest.time)
}

// -------------------------------------------------------------------

// RecordingStatusReply

// optional .mearec.RecordingStatusReply.StatusType status = 1;
inline bool RecordingStatusReply::has_status() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RecordingStatusReply::set_has_status() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RecordingStatusReply::clear_has_status() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RecordingStatusReply::clear_status() {
  status_ = 0;
  clear_has_status();
}
inline ::mearec::RecordingStatusReply_StatusType RecordingStatusReply::status() const {
  // @@protoc_insertion_point(field_get:mearec.RecordingStatusReply.status)
  return static_cast< ::mearec::RecordingStatusReply_StatusType >(status_);
}
inline void RecordingStatusReply::set_status(::mearec::RecordingStatusReply_StatusType value) {
  assert(::mearec::RecordingStatusReply_StatusType_IsValid(value));
  set_has_status();
  status_ = value;
  // @@protoc_insertion_point(field_set:mearec.RecordingStatusReply.status)
}

// optional string filename = 2;
inline bool RecordingStatusReply::has_filename() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RecordingStatusReply::set_has_filename() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RecordingStatusReply::clear_has_filename() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RecordingStatusReply::clear_filename() {
  if (filename_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    filename_->clear();
  }
  clear_has_filename();
}
inline const ::std::string& RecordingStatusReply::filename() const {
  // @@protoc_insertion_point(field_get:mearec.RecordingStatusReply.filename)
  return *filename_;
}
inline void RecordingStatusReply::set_filename(const ::std::string& value) {
  set_has_filename();
  if (filename_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    filename_ = new ::std::string;
  }
  filename_->assign(value);
  // @@protoc_insertion_point(field_set:mearec.RecordingStatusReply.filename)
}
inline void RecordingStatusReply::set_filename(const char* value) {
  set_has_filename();
  if (filename_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    filename_ = new ::std::string;
  }
  filename_->assign(value);
  // @@protoc_insertion_point(field_set_char:mearec.RecordingStatusReply.filename)
}
inline void RecordingStatusReply::set_filename(const char* value, size_t size) {
  set_has_filename();
  if (filename_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    filename_ = new ::std::string;
  }
  filename_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:mearec.RecordingStatusReply.filename)
}
inline ::std::string* RecordingStatusReply::mutable_filename() {
  set_has_filename();
  if (filename_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    filename_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:mearec.RecordingStatusReply.filename)
  return filename_;
}
inline ::std::string* RecordingStatusReply::release_filename() {
  clear_has_filename();
  if (filename_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = filename_;
    filename_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void RecordingStatusReply::set_allocated_filename(::std::string* filename) {
  if (filename_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete filename_;
  }
  if (filename) {
    set_has_filename();
    filename_ = filename;
  } else {
    clear_has_filename();
    filename_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:mearec.RecordingStatusReply.filename)
}

// optional double length = 3;
inline bool RecordingStatusReply::has_length() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void RecordingStatusReply::set_has_length() {
  _has_bits_[0] |= 0x00000004u;
}
inline void RecordingStatusReply::clear_has_length() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void RecordingStatusReply::clear_length() {
  length_ = 0;
  clear_has_length();
}
inline double RecordingStatusReply::length() const {
  // @@protoc_insertion_point(field_get:mearec.RecordingStatusReply.length)
  return length_;
}
inline void RecordingStatusReply::set_length(double value) {
  set_has_length();
  length_ = value;
  // @@protoc_insertion_point(field_set:mearec.RecordingStatusReply.length)
}

// optional uint32 nsamples = 4;
inline bool RecordingStatusReply::has_nsamples() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void RecordingStatusReply::set_has_nsamples() {
  _has_bits_[0] |= 0x00000008u;
}
inline void RecordingStatusReply::clear_has_nsamples() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void RecordingStatusReply::clear_nsamples() {
  nsamples_ = 0u;
  clear_has_nsamples();
}
inline ::google::protobuf::uint32 RecordingStatusReply::nsamples() const {
  // @@protoc_insertion_point(field_get:mearec.RecordingStatusReply.nsamples)
  return nsamples_;
}
inline void RecordingStatusReply::set_nsamples(::google::protobuf::uint32 value) {
  set_has_nsamples();
  nsamples_ = value;
  // @@protoc_insertion_point(field_set:mearec.RecordingStatusReply.nsamples)
}

// optional uint32 nchannels = 5;
inline bool RecordingStatusReply::has_nchannels() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void RecordingStatusReply::set_has_nchannels() {
  _has_bits_[0] |= 0x00000010u;
}
inline void RecordingStatusReply::clear_has_nchannels() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void RecordingStatusReply::clear_nchannels() {
  nchannels_ = 0u;
  clear_has_nchannels();
}
inline ::google::protobuf::uint32 RecordingStatusReply::nchannels() const {
  // @@protoc_insertion_point(field_get:mearec.RecordingStatusReply.nchannels)
  return nchannels_;
}
inline void RecordingStatusReply::set_nchannels(::google::protobuf::uint32 value) {
  set_has_nchannels();
  nchannels_ = value;
  // @@protoc_insertion_point(field_set:mearec.RecordingStatusReply.nchannels)
}

// optional uint32 lastValidSample = 6;
inline bool RecordingStatusReply::has_lastvalidsample() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void RecordingStatusReply::set_has_lastvalidsample() {
  _has_bits_[0] |= 0x00000020u;
}
inline void RecordingStatusReply::clear_has_lastvalidsample() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void RecordingStatusReply::clear_lastvalidsample() {
  lastvalidsample_ = 0u;
  clear_has_lastvalidsample();
}
inline ::google::protobuf::uint32 RecordingStatusReply::lastvalidsample() const {
  // @@protoc_insertion_point(field_get:mearec.RecordingStatusReply.lastValidSample)
  return lastvalidsample_;
}
inline void RecordingStatusReply::set_lastvalidsample(::google::protobuf::uint32 value) {
  set_has_lastvalidsample();
  lastvalidsample_ = value;
  // @@protoc_insertion_point(field_set:mearec.RecordingStatusReply.lastValidSample)
}

// optional uint32 blockSize = 7;
inline bool RecordingStatusReply::has_blocksize() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void RecordingStatusReply::set_has_blocksize() {
  _has_bits_[0] |= 0x00000040u;
}
inline void RecordingStatusReply::clear_has_blocksize() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void RecordingStatusReply::clear_blocksize() {
  blocksize_ = 0u;
  clear_has_blocksize();
}
inline ::google::protobuf::uint32 RecordingStatusReply::blocksize() const {
  // @@protoc_insertion_point(field_get:mearec.RecordingStatusReply.blockSize)
  return blocksize_;
}
inline void RecordingStatusReply::set_blocksize(::google::protobuf::uint32 value) {
  set_has_blocksize();
  blocksize_ = value;
  // @@protoc_insertion_point(field_set:mearec.RecordingStatusReply.blockSize)
}

// optional float sampleRate = 8;
inline bool RecordingStatusReply::has_samplerate() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void RecordingStatusReply::set_has_samplerate() {
  _has_bits_[0] |= 0x00000080u;
}
inline void RecordingStatusReply::clear_has_samplerate() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void RecordingStatusReply::clear_samplerate() {
  samplerate_ = 0;
  clear_has_samplerate();
}
inline float RecordingStatusReply::samplerate() const {
  // @@protoc_insertion_point(field_get:mearec.RecordingStatusReply.sampleRate)
  return samplerate_;
}
inline void RecordingStatusReply::set_samplerate(float value) {
  set_has_samplerate();
  samplerate_ = value;
  // @@protoc_insertion_point(field_set:mearec.RecordingStatusReply.sampleRate)
}

// optional float gain = 9;
inline bool RecordingStatusReply::has_gain() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void RecordingStatusReply::set_has_gain() {
  _has_bits_[0] |= 0x00000100u;
}
inline void RecordingStatusReply::clear_has_gain() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void RecordingStatusReply::clear_gain() {
  gain_ = 0;
  clear_has_gain();
}
inline float RecordingStatusReply::gain() const {
  // @@protoc_insertion_point(field_get:mearec.RecordingStatusReply.gain)
  return gain_;
}
inline void RecordingStatusReply::set_gain(float value) {
  set_has_gain();
  gain_ = value;
  // @@protoc_insertion_point(field_set:mearec.RecordingStatusReply.gain)
}

// optional float offset = 10;
inline bool RecordingStatusReply::has_offset() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void RecordingStatusReply::set_has_offset() {
  _has_bits_[0] |= 0x00000200u;
}
inline void RecordingStatusReply::clear_has_offset() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void RecordingStatusReply::clear_offset() {
  offset_ = 0;
  clear_has_offset();
}
inline float RecordingStatusReply::offset() const {
  // @@protoc_insertion_point(field_get:mearec.RecordingStatusReply.offset)
  return offset_;
}
inline void RecordingStatusReply::set_offset(float value) {
  set_has_offset();
  offset_ = value;
  // @@protoc_insertion_point(field_set:mearec.RecordingStatusReply.offset)
}

// optional string date = 11;
inline bool RecordingStatusReply::has_date() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void RecordingStatusReply::set_has_date() {
  _has_bits_[0] |= 0x00000400u;
}
inline void RecordingStatusReply::clear_has_date() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void RecordingStatusReply::clear_date() {
  if (date_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    date_->clear();
  }
  clear_has_date();
}
inline const ::std::string& RecordingStatusReply::date() const {
  // @@protoc_insertion_point(field_get:mearec.RecordingStatusReply.date)
  return *date_;
}
inline void RecordingStatusReply::set_date(const ::std::string& value) {
  set_has_date();
  if (date_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    date_ = new ::std::string;
  }
  date_->assign(value);
  // @@protoc_insertion_point(field_set:mearec.RecordingStatusReply.date)
}
inline void RecordingStatusReply::set_date(const char* value) {
  set_has_date();
  if (date_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    date_ = new ::std::string;
  }
  date_->assign(value);
  // @@protoc_insertion_point(field_set_char:mearec.RecordingStatusReply.date)
}
inline void RecordingStatusReply::set_date(const char* value, size_t size) {
  set_has_date();
  if (date_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    date_ = new ::std::string;
  }
  date_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:mearec.RecordingStatusReply.date)
}
inline ::std::string* RecordingStatusReply::mutable_date() {
  set_has_date();
  if (date_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    date_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:mearec.RecordingStatusReply.date)
  return date_;
}
inline ::std::string* RecordingStatusReply::release_date() {
  clear_has_date();
  if (date_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = date_;
    date_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void RecordingStatusReply::set_allocated_date(::std::string* date) {
  if (date_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete date_;
  }
  if (date) {
    set_has_date();
    date_ = date;
  } else {
    clear_has_date();
    date_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:mearec.RecordingStatusReply.date)
}

// optional string time = 12;
inline bool RecordingStatusReply::has_time() const {
  return (_has_bits_[0] & 0x00000800u) != 0;
}
inline void RecordingStatusReply::set_has_time() {
  _has_bits_[0] |= 0x00000800u;
}
inline void RecordingStatusReply::clear_has_time() {
  _has_bits_[0] &= ~0x00000800u;
}
inline void RecordingStatusReply::clear_time() {
  if (time_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    time_->clear();
  }
  clear_has_time();
}
inline const ::std::string& RecordingStatusReply::time() const {
  // @@protoc_insertion_point(field_get:mearec.RecordingStatusReply.time)
  return *time_;
}
inline void RecordingStatusReply::set_time(const ::std::string& value) {
  set_has_time();
  if (time_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    time_ = new ::std::string;
  }
  time_->assign(value);
  // @@protoc_insertion_point(field_set:mearec.RecordingStatusReply.time)
}
inline void RecordingStatusReply::set_time(const char* value) {
  set_has_time();
  if (time_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    time_ = new ::std::string;
  }
  time_->assign(value);
  // @@protoc_insertion_point(field_set_char:mearec.RecordingStatusReply.time)
}
inline void RecordingStatusReply::set_time(const char* value, size_t size) {
  set_has_time();
  if (time_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    time_ = new ::std::string;
  }
  time_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:mearec.RecordingStatusReply.time)
}
inline ::std::string* RecordingStatusReply::mutable_time() {
  set_has_time();
  if (time_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    time_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:mearec.RecordingStatusReply.time)
  return time_;
}
inline ::std::string* RecordingStatusReply::release_time() {
  clear_has_time();
  if (time_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = time_;
    time_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void RecordingStatusReply::set_allocated_time(::std::string* time) {
  if (time_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete time_;
  }
  if (time) {
    set_has_time();
    time_ = time;
  } else {
    clear_has_time();
    time_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:mearec.RecordingStatusReply.time)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace mearec

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::mearec::RecordingStatusReply_StatusType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::mearec::RecordingStatusReply_StatusType>() {
  return ::mearec::RecordingStatusReply_StatusType_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_logserver_2eproto__INCLUDED
